### ISSUE TITLE
Tell npm users more clearly that the version on NPM does contain the dist files

### ISSUE THREAD

**Issue by mk-pmb** [norbertvolf/openui5-dist#1]
Hi! The package name, combined with a lack of an "openui5" package on npm, conjured up an expectation so strong that I only read the first line of your description before I jumped to the conclusion it would be just build instructions for how to update this package. Could you put a more dire warning in front that no actual dist files are included here?

**Comment by norbertvolf** [comment]
Hi,
I have improved the README. The repository in github contains only building script. NPM package in npmjs.com contains OpenUI5 distribution and you can use it for building OpenUI5 app. I have prepared also example app. Just check the [README](https://github.com/norbertvolf/openui5-dist). I hope it is better now.

**Comment by mk-pmb** [comment]
Much better, thanks! Now that I understand the facts, allow me to suggest an even more succinct version of the first sentence, that also makes it more clear for people who read the description on Github:

```diff
 The
+NPM
 package contains
+the
 OpenUI5 framework
-packaged for NPM
 and the script for
-the
 building the
-OpenUI5 framework for
 NPM package.
```

&rArr; The NPM package contains the OpenUI5 framework and the script for building the NPM package.
